name: Trigger Release

on:
  workflow_dispatch:

jobs:
  archive:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          ref: main
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Python environment
        uses: ./.github/actions/setup-python

      - run: echo "TAG_NAME=v$(pdm show --version)" >> $GITHUB_ENV

      - name: Push Tag
        run: |
          git config user.name github-actions[bot]
          git config user.email github-actions[bot]@users.noreply.github.com
          git add .
          git commit -m ":bookmark: Release $(poetry version -s)"
          git tag ${{ env.TAG_NAME }}
          git push && git push --tags
