name: Release

on:
  push:
    tags:
      - v*

jobs:
  publish-pypi-github:
    runs-on: ubuntu-latest
    permissions:
      # write permission is required to create a github release
      contents: write
      # write permission is required for autolabeler
      # otherwise, read permission is required at least
      pull-requests: write
    steps:
      - uses: actions/checkout@v4

      - name: Setup Python environment
        uses: ./.github/actions/setup-python

      - run: |
          echo "TAG_NAME=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      - uses: release-drafter/release-drafter@v6
        with:
          name: Release ${{ env.TAG_NAME }}
          tag: ${{ env.TAG_NAME }}
          publish: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish PyPI and Github
        run: |
          pdm publish
          gh release upload --clobber ${{ env.TAG_NAME }} dist/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
